src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;


    public function getId(): ?int
    {
        return $this->id;
    }
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity=Tag::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tag;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="products")
     */
    private $creator;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="product")
     */
    private $questions;

    public function __construct()
    {
        $this->questions = new ArrayCollection();
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }
    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;

    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }
    public function setTag(?Tag $tag): self
    {
        $this->tag = $tag;

        return $this;
    }
    public function getTag(): ?Tag
    {
        return $this->tag;
    }
    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setProduct($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->removeElement($question)) {
            // set the owning side to null (unless already changed)
            if ($question->getProduct() === $this) {
                $question->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\AddToCartType;
use App\Manager\CartManager;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\CreateProductForm;
use App\Form\AddQuestionType;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Question;


/**
 * Class ProductController
 * @package App\Controller
 */
class ProductController extends AbstractController
{
    /**
     * @Route("/product/{id}", name="product.detail", methods={"GET", "POST"})
     * @param String $id
     * @param ProductRepository $productRepository
     * @return Response
     */
    public function detail(string $id, ProductRepository $productRepository, Product $product, Request $request, CartManager $cartManager, EntityManagerInterface $em ): Response
    {
        $question = new Question();
        $fo = $this->createForm(AddQuestionType::class, $question);
        $fo->handleRequest($request);
        if ($fo->isSubmitted() && $fo->isValid()) {
            $question = $fo->getData();
            $question->setCreator($this->getUser());
            $product->addQuestion($question);
            $em->persist($question);
            $em->flush();
        }

        $form = $this->createForm(AddToCartType::class);
        $form->handleRequest($request);
        if($form->isSubmitted() &&  $form->isValid()){
            $item = $form->getData();
            $item->setProduct($product);
            $cart = $cartManager->getCurrentCart();
            $cart
                ->addItem($item)
                ->setUpdatedAt(new \DateTime());
            
            $cartManager->save($cart);
            return $this->redirectToRoute('product.detail',['id' => $product->getId()]);
            
        }

        return $this->render('product/detail.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
            'questionform' => $fo->createView(),
        ]);
    }
    /**
     * @Route("addProducts", name="addProducts", methods={"GET", "POST"})
     * @param Request $request
     * @return Response
     */
    public function addProducts(Request $request, EntityManagerInterface $em): Response
    {
        $product = new Product();
        $form = $this->createForm(CreateProductForm::class);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $product = $form->getData();
            $product->setCreator($this->getUser());
            $product->setDate(new \DateTime());

            $em->persist($product);
            $em->flush();
            return $this->redirectToRoute('home');
        }
        return $this->render('product/addProducts.html.twig', [
            'addForm' => $form->createView(),
        ]);
    }
    /**
     * @Route("/product/delete/{id}", name="product.delete")
     */
    public function delete(Product $product, EntityManagerInterface $em): Response
    {
        $em->remove($product);
        $em->flush();
        return $this->redirectToRoute('home');
    }
    // Edit button
    /**
     * @Route("/product/edit/{id}", name="product.edit")
     */
    public function edit(Product $product, Request $request, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(CreateProductForm::class, $product);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $product = $form->getData();
            $product->setCreator($this->getUser());
            $product->setDate(new \DateTime());

            $em->persist($product);
            $em->flush();
            return $this->redirectToRoute('home');
        }
        return $this->render('product/edit.html.twig', [
            'editForm' => $form->createView(),
        ]);
    }
}

templates/product/addProducts.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un Produit{% endblock %}

{% block body %}

    <h1>Ajouter un produit</h1>

{% if(app.user == null) %}
    <div class="alert alert-primary d-flex flex-column mt-4" role="alert">
        <p class="lh-1">Vous devez être connecté pour ajouter un produit !<p>
        <a href="{{ path('login') }}">Login!</a>                
    </div>
{% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
               {{ form_start(addForm) }}
               {{ form_widget(addForm) }}
               <button class="btn btn-primary mt-3" type="submit">Ajouter</button>
               {{ form_end(addForm) }}
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}

templates/product/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ product.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mt-3 mb-4">
            <div class="col-md-4">
                <img src="https://via.placeholder.com/600x400" alt=" {{ product.name }}" class="img-fluid">
                <h5><b> Tags: </b> {{ product.tag.name }}</h5>
            </div>
            <div class="col-md-8">
                <h1 class="mt-4 mt-md-0"> {{ product.name }} </h1>
                <h2> {{ product.price }} € </h2>
                <hr>
                <b> Description: </b> {{ product.description }}
                <br>
                <b> Publié le: </b> {{ product.date|date('d/m/Y') }}           
                    {% if app.user is same as (product.creator) and app.user != null %}
                    <form action="{{ path('product.delete', {'id': product.id}) }}" method="post">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
                        <button type="submit" class="btn btn-danger">Supprimer</button>
                    </form>
                    <form action="{{ path('product.edit', {'id': product.id}) }}" method="get">
                        <button type="submit" class="btn btn-primary">Modifier</button>
                    </form>

                {% else %}
                {{ form_start(form, {'attr': {'class': 'mt-4 p-4 bg-light'}})}}
                    <div class="form-group">
                        {{ form_label(form.quantity) }}
                        {{ form_widget(form.quantity, {
                            'attr': {
                                'class': 'form-control ' ~ (form.quantity.vars.valid ? '' : 'is-invalid')
                                }
                                }) }}
                        <div class="invalid-feedback">
                            {{ form_errors(form.quantity) }}
                        </div>
                    </div>
                {{ form_widget(form.add, {'attr': {'class': 'btn btn-warning  w-25'}}) }}
                {{ form_end(form) }}
                {% endif %}
            {# Questions #}
                <div class="mt-4">
                    <h3>Questions</h3>
                    <hr>
                    {% for question in product.questions %}
                    <div class="media">
                        <div class="media-body">
                            <p>{{ question.content }}</p>
                            <p class="text-right">
                                <small class="text-muted">
                                    Posée par : {{ question.creator.email }}
                                </small>
                                <hr>
                                
                        </div>
                        
                    </div>
                    {% endfor %}
                    {% if app.user == null %}
                    <div class="alert alert-info mt-4" role="alert">
                        <p>Vous devez être connecté pour poser une question </p>
                    </div>
                    {% else %}
                    {{ form_start(questionform, {'attr': {'class': 'mt-4 p-4 bg-light'}})}}
                    {{ form_row(questionform.content, {'attr': {'class': 'form-control'}}) }}
                    <button class="btn btn-primary mt-3" type="submit">Ajouter une question</button>
                    {{ form_end(questionform) }}
                    {% endif %}

            </div>
            {# End Questions #}
        </div>
    </div>
    
{% endblock %}

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un produit{% endblock %}

{% block body %}

    <h1>Modifier un produit</h1>

{% if(app.user == null) %}
    <div class="alert alert-primary d-flex flex-column mt-4" role="alert">
        <p class="lh-1">Vous devez être connecté pour modifier un produit<p>
        <a href="{{ path('login') }}">Go login!</a>                
    </div>
{% else %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
               {{ form_start(editForm) }}
               {{ form_widget(editForm) }}
               <button class="btn btn-primary mt-3" type="submit">Add</button>
               {{ form_end(editForm) }}
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}